# Generated by Django 3.1.7 on 2021-03-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_comment_commentposition_commentreply'),
        ('wagtailcore', '0061_change_promote_tab_helpt_text_and_verbose_names'),
    ]

    operations = [
    ]
